<template>
	<div>
		<h1>/index route!</h1>
		<p>
			These links are generated by
			<code>$typedRouter.resolve and &lt;NuxtLink :to=""</code>
		</p>
		<br />
		<NuxtLink :to="$typedRouter.resolve({ name: 'about' })"
			>Go to /about</NuxtLink
		>
		<br />
		<NuxtLink :to="$typedRouter.resolve({ name: 'deeply-nested-route' })"
			>Go to /deeply/nested/route</NuxtLink
		>

		<h2>
			This link behind that button was generated by useTypedRouter inside the
			&lt;script&gt; tag
		</h2>
		<button @click="handleRedirect">Trigger redirect to /about</button>
	</div>
</template>

<script setup lang="ts">
	import { useTypedRouter } from '@/types/generated'
	const { router } = useTypedRouter()

	const handleRedirect = () => {
		router.push({ name: 'about' })
	}
</script>
